check-syntax:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq lua5.1
    - lua5.1 -v
    - .ci-scripts/check-syntax.sh

glualint:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq unzip curl ca-certificates libgmp10
    - .ci-scripts/download-glualint.sh
    - .ci-scripts/glualint.sh
