language: python
sudo: false

addons:
  apt:
    packages:
    - unzip
    - lua5.1

before_install:
  - BINDIR="$(mktemp -d --suffix .bindir)"
  - mkdir -p "${BINDIR}/bin"
  - .travis-ci/download-glualint.sh "${BINDIR}/bin"
  - export PATH=$PATH:${BINDIR}/bin

script:
  - .travis-ci/check-syntax.sh "$TRAVIS_BUILD_DIR"
  - .travis-ci/check-glualint.sh "$TRAVIS_BUILD_DIR"

after_script:
  - rm -rf "${BINDIR}"

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
